# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.18.0"

[[constraint]]
  name = "github.com/aws/aws-xray-sdk-go"
  version = "0.9.4"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  branch = "master"
  name = "github.com/luna-duclos/instrumentedsql"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
